spring:
  application:
    name: xj-tysfrz-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8080}

app:
  info:
    platform-name: 高校综合身份数据平台
    release: @project.version@
    maintenance: false

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: ${SA_TOKEN_TIMEOUT:28800}
  active-timeout: -1
  is-concurrent: true
  is-share: false
  is-log: false
  is-read-header: true
  is-read-cookie: false
  is-read-body: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  info:
    build:
      enabled: true
    git:
      mode: full

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
